# Generated by Django 4.2.2 on 2023-07-10 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='number_downloads',
            field=models.IntegerField(default=0, verbose_name='Número de descagas'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='libros', verbose_name='imagen'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='book_files')),
                ('number_pages', models.IntegerField(verbose_name='Número de páginas')),
                ('number_downloads', models.IntegerField(verbose_name='Número de descagas')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book', verbose_name='Libro')),
                ('typeFile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.typefile', verbose_name='Tipo de archivo')),
            ],
        ),
    ]
