# Generated by Django 4.2.2 on 2023-07-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_typefile_book_number_downloads_alter_book_image_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Lenguaje')),
            ],
            options={
                'verbose_name': 'Lenguaje',
                'verbose_name_plural': 'Lenguajes',
                'ordering': ['-name'],
            },
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-created'], 'verbose_name': 'Archivo', 'verbose_name_plural': 'Archivos'},
        ),
        migrations.AlterModelOptions(
            name='typefile',
            options={'ordering': ['-name'], 'verbose_name': 'Tipo de archivo', 'verbose_name_plural': 'tipos de archivos'},
        ),
        migrations.RenameField(
            model_name='typefile',
            old_name='nombre',
            new_name='name',
        ),
    ]
