# Generated by Django 4.2.2 on 2023-07-10 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_language_alter_file_options_alter_typefile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.language', verbose_name='Lenguaje'),
        ),
    ]
