# Generated by Django 4.2.2 on 2023-07-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_file_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Archivo', 'verbose_name_plural': 'Archivos'},
        ),
        migrations.RemoveField(
            model_name='file',
            name='created',
        ),
        migrations.RemoveField(
            model_name='file',
            name='updated',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='book_files', verbose_name='Archivo'),
        ),
    ]
