# Generated by Django 4.2.2 on 2023-06-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Categoría de animación',
                'verbose_name_plural': 'Categorías de animación',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ['-created'], 'verbose_name': 'Animación', 'verbose_name_plural': 'Animaciones'},
        ),
        migrations.AddField(
            model_name='anime',
            name='categories',
            field=models.ManyToManyField(to='anime.categories', verbose_name='Categorías'),
        ),
    ]
