# Generated by Django 4.2.2 on 2023-06-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_studio'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='studios',
            field=models.ManyToManyField(to='anime.studio', verbose_name='Estudios'),
        ),
    ]
