# Generated by Django 4.2.2 on 2023-06-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_alter_author_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='author', verbose_name='imagen'),
        ),
    ]
